### PR TITLE
Fixing login and signup danny

### LINKED ISSUE #47: Fixed login page

### PR DESCRIPTION
**Pull request by DNiev**
closes #47

### CODE REVIEW

**Review by tracilevine — APPROVED** [review]

File: client/src/pages/Signup.js [hunk 1]
```diff
@@ -1,16 +1,18 @@
...
 import swal from 'sweetalert';
+import '../components/styles/login.css';
 
 const SignUp = ({ history }) => {
   const { setCurrentUser } = useContext(AppContext);
   const [formData, setFormData] = useState(null);
 
   const handleChange = (event) => {
     setFormData({ ...formData, [event.target.name]: event.target.value });
+    console.log(formData);
```
Comment (ErnieAtLYD) [inline client/src/pages/Signup.js:15]: `sideeye.gif` at the random `console.log()`. Kill the console.logs once you're done using them.

File: client/src/pages/Signup.js [hunk 2]
```diff
@@ -30,65 +32,76 @@ const SignUp = ({ history }) => {
...
-        <p>or</p>
-        <hr />
-        <h2>Sign up with your email address</h2>
-        <Link to="/login">Have an account? Login</Link>
-      </div>
       <Form onSubmit={handleSignUp} className="d-flex flex-column">
+        <h1 className="m-auto">Welcome to The Bike Shop!</h1>
+
+        <Form.Label className="text-center">
+          {' '}
```
Comment (ErnieAtLYD) [inline client/src/pages/Signup.js:39]: You don't need this line.

**Review by ErnieAtLYD — APPROVED** [review]
This looks good too - I'll approve without merging because there are things here you could probably make a little better.
